/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminHeader: typeof import('./src/components/Admin/Header.vue')['default']
    BookingConfirmDialog: typeof import('./src/components/Booking/DoneConfirmationDialog.vue')['default']
    BookingDeleteDialog: typeof import('./src/components/Booking/DeleteDialog.vue')['default']
    BookingDokterDeleteDialog: typeof import('./src/components/Booking/Dokter/DeleteDialog.vue')['default']
    BookingDoneConfirmationDialog: typeof import('./src/components/Booking/DoneConfirmationDialog.vue')['default']
    BookingForm: typeof import('./src/components/BookingForm.vue')['default']
    BookingFormSelect: typeof import('./src/components/BookingForm/SelectTime.vue')['default']
    BookingFormSelectTime: typeof import('./src/components/BookingForm/SelectTime.vue')['default']
    copy: typeof import('./src/components/Booking/Dokter/DeleteDialog copy.vue')['default']
    DatePicker: typeof import('./src/components/DatePicker.vue')['default']
    DeleteDialog: typeof import('./src/components/Dokter/DeleteDialog.vue')['default']
    DoktercopyDeleteDialog: typeof import('./src/components/Dokter copy/DeleteDialog.vue')['default']
    DokterDeleteDialog: typeof import('./src/components/Dokter/DeleteDialog.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    Hero: typeof import('./src/components/Hero.vue')['default']
    LoadingScreen: typeof import('./src/components/loadingScreen.vue')['default']
    PasienDeleteDialog: typeof import('./src/components/Pasien/DeleteDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./src/components/Select.vue')['default']
  }
}
