/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/admin': RouteRecordInfo<'/admin', '/admin', Record<never, never>, Record<never, never>>,
    '/auth/login': RouteRecordInfo<'/auth/login', '/auth/login', Record<never, never>, Record<never, never>>,
    '/auth/register': RouteRecordInfo<'/auth/register', '/auth/register', Record<never, never>, Record<never, never>>,
    '/booking-darurat/': RouteRecordInfo<'/booking-darurat/', '/booking-darurat', Record<never, never>, Record<never, never>>,
    '/booking-darurat/antrian': RouteRecordInfo<'/booking-darurat/antrian', '/booking-darurat/antrian', Record<never, never>, Record<never, never>>,
    '/booking-darurat/select': RouteRecordInfo<'/booking-darurat/select', '/booking-darurat/select', Record<never, never>, Record<never, never>>,
    '/jadwal-pengobatan/': RouteRecordInfo<'/jadwal-pengobatan/', '/jadwal-pengobatan', Record<never, never>, Record<never, never>>,
    '/jadwal-pengobatan/tiket': RouteRecordInfo<'/jadwal-pengobatan/tiket', '/jadwal-pengobatan/tiket', Record<never, never>, Record<never, never>>,
    '/profile/': RouteRecordInfo<'/profile/', '/profile', Record<never, never>, Record<never, never>>,
    '/profile/riwayat/': RouteRecordInfo<'/profile/riwayat/', '/profile/riwayat', Record<never, never>, Record<never, never>>,
    '/profile/riwayat/[id]/': RouteRecordInfo<'/profile/riwayat/[id]/', '/profile/riwayat/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
  }
}
